apiVersion: v1
kind: Service
metadata:
  name: redis-operator-controller-manager
  namespace: redis-operator-system
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/component: controller-manager
spec:
  selector:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/component: controller-manager
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
