apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "redis-operator.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
