apiVersion: v1
kind: Service
metadata:
  name: redis-operator-webhook-service
  namespace: redis-operator-system
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/component: webhook
spec:
  selector:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/component: controller-manager
  ports:
    - name: https
      port: 443
      targetPort: webhook
      protocol: TCP
