apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator-controller-manager
  namespace: redis-operator-system
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/component: controller-manager
